version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    command:
      - sh
      - -c
      - |
        bin/elasticsearch-plugin install analysis-nori &&
        bin/elasticsearch-plugin install analysis-kuromoji &&
        bin/elasticsearch-plugin install analysis-icu &&
        /usr/local/bin/docker-entrypoint.sh
volumes:
  esdata1:
    driver: local
